### ISSUE TITLE
dataset_neck_skin_correction.py

### ISSUE THREAD

**Issue by nandu749** [minar09/cp-vton-plus#3] opened 2020-07-07 06:00 UTC
Got error FileNotFoundError: [Errno 2] No such file or directory: 'data/viton_resize/train/image'

**Comment by minar09** [comment] 2020-07-07 06:49
Hi @nandu749 , I think you need to download the dataset first. Please run the data_download.py file. Thanks.

**Comment by nandu749** [comment] 2020-07-07 06:59
ok, but missing files test_pairs.txt, and what is image-mask, is it different from image-parse. Got an error FileNotFoundError: [Errno 2] No such file or directory: 'data/test/image-mask/000001_0.png'.

**Comment by nandu749** [comment] 2020-07-07 07:01
after downloading the dataset the 'data/viton_resize/train/image', 'data/viton_resize/train/image-parse', 'data/viton_resize/train/image-mask' directory is missing. I created the directory but after running dataset_neck_skin_correction.py,  body_binary_masking.py didn't find any changes.

**Comment by nandu749** [comment] 2020-07-07 07:03
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/image-mask/000001_0.png'. happens when I run python test.py --name GMM --stage GMM --workers 4 --datamode test --data_list test_pairs.txt --checkpoint checkpoints/GMM/gmm_final.pth

**Comment by minar09** [comment] 2020-07-07 07:18
Hi, I uploaded the pairs files in the data/ folder (They should be included in dataset too.)

If you run the Data Preparation steps, it will do the following:

1) data_download.py: Download the full dataset into data/ folder, both train and test.
2) dataset_neck_skin_correction.py: Add a new segmentation label for neck/skin areas, and save the new segmentation in "image-parse-new" folder. You need to run twice for both train and test data.
3) body_binary_masking.py: It will create the body binary masks for using as in the inputs of the networks. You need to run twice for both train and test data.

Hope that helps! Thank you.

**Comment by minar09** [comment] 2020-07-07 07:21
I updated the repo and the readme file. Please check again. Thanks.

**Comment by nandu749** [comment] 2020-07-07 07:24
Do I need to run 2 time dataset_neck_skin_correction.py, body_binary_masking.py?

**Comment by minar09** [comment] 2020-07-07 07:25
Yes, both of them, for train and test data separately. Please set the folder paths correctly before running.

**Comment by nandu749** [comment] 2020-07-07 07:27
I am going for the testing from your checkpoints. just running these scripts is enough or should I have to create directories such as image-parse, image-mask?, and I didn't see any directory named image-mask but throwing error?

**Comment by minar09** [comment] 2020-07-07 07:27
By the way, if you just want to test, you can just run for test data only. And vice versa for training. Or both if you want to do both.

**Comment by nandu749** [comment] 2020-07-07 07:27
Can you guide me the path for testing, running on Google colab

**Comment by nandu749** [comment] 2020-07-07 07:29
https://colab.research.google.com/drive/1nfxC6frMmnQHuFdq1rnBZT_95VMHoEAr?usp=sharing

**Comment by minar09** [comment] 2020-07-07 07:29
"image-mask" folder will be created when you run body_binary_masking.py. You don't need to create any folder.

**Comment by nandu749** [comment] 2020-07-07 07:30
can you look at the colab notebook?

**Comment by nandu749** [comment] 2020-07-07 07:32
Working in it for couple of hours but can't figure it out

**Comment by minar09** [comment] 2020-07-07 07:34
Yes, I did. I set the paths for test by default. Please clone as new again. And you can just run them one by one.

**Comment by nandu749** [comment] 2020-07-07 07:36
ohk, lemme try, thanks for your fast reply

**Comment by minar09** [comment] 2020-07-07 07:37
Great! Thanks.

**Comment by nandu749** [comment] 2020-07-07 08:15
![ss](https://user-images.githubusercontent.com/66773583/86745658-21815300-c058-11ea-91f4-14c651bc8629.png)

**Comment by nandu749** [comment] 2020-07-07 08:17
root_dir = "data/viton_resize"
    updated_seg_folder = "image-parse-new"

    # data_mode = "train"
    data_mode = "test"
    image_folder = "image"
    seg_folder = "image-parse"
why viton_resize? , image-parse-new, image-parse it is not used in test?

**Comment by nandu749** [comment] 2020-07-07 08:25
I changed to root_dir = "data/" and it now works

**Comment by minar09** [comment] 2020-07-07 08:39
Great! Thanks for pointing this out. I am updating the paths in the files. "image-parse" contains the original segmentation from the dataset because it does not have a label for neck/skin/chest areas. We add a new label for these skin areas by running dataset_neck_skin_correction.py and save them in the "image-parse-new" folder. You can check our paper for more details. Thank you.

**Comment by nandu749** [comment] 2020-07-07 09:17
![Screenshot from 2020-07-07 14-45-18](https://user-images.githubusercontent.com/66773583/86757391-bbe59480-c060-11ea-990f-8eb37a71f0a3.png)

**Comment by nandu749** [comment] 2020-07-07 09:18
I think image size problem is there, since the tensor size does't match

**Comment by thaithanhtuan** [comment] 2020-07-07 09:33
![](https://user-images.githubusercontent.com/66773583/86757391-bbe59480-c060-11ea-990f-8eb37a71f0a3.png)
This comes from different version of PyTorch. To fix this error. First. Open file cp_dataset.py and add this:
```
self.transform = transforms.Compose([  \
                transforms.ToTensor(),   \
                transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
#line 33
self.transformmask = transforms.Compose([ \
            transforms.ToTensor(), \
            transforms.Normalize((0.5,), (0.5,))])
```
Then change line 138 from:
`shape_ori = self.transform(parse_shape_ori)  # [-1,1]`
to:
`shape_ori = self.transformmask(parse_shape_ori)  # [-1,1]`
This error may happen to other parts of the code.

**Comment by minar09** [comment] 2020-07-07 09:40
Hi @nandu749 , I submitted a fix for new segmentation.  Can you please try with the updated code? Thanks. Sorry for your inconvenience. You can also try the suggestion from @thaithanhtuan .

**Comment by nandu749** [comment] 2020-07-07 10:30
you can update the code for torch-1.5.1, the repo is for torch==0.4.1

**Comment by nandu749** [comment] 2020-07-07 10:33
if using torch==0.4.1 use Pillow==6.1else it will throw error like ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (unknown location)

**Comment by minar09** [comment] 2020-07-07 10:36
I think you need to install torch==0.4.1 to test with the pretrained checkpoints.

**Comment by nandu749** [comment] 2020-07-07 10:38
GMM test should save the results in "data/viton_resize/test", that is the directories such as warp-cloth, warp-mask, warped-grid, result_dir, overlayed_TPS should present inside"data/viton_resize/test"

**Comment by nandu749** [comment] 2020-07-07 10:40
yeah 

> I think you need to install torch==0.4.1 to test with the pretrained checkpoints.

yeah, done it , that's why pillow thrown an error(pip install pillow==6.1 solves it)

**Comment by nandu749** [comment] 2020-07-07 15:22
![final](https://user-images.githubusercontent.com/66773583/86803546-b7869f00-c093-11ea-98ed-c747a13f1f97.png)

**Comment by nandu749** [comment] 2020-07-07 15:22
the results are like this from the ckeckpoints

**Comment by armheb** [comment] 2020-07-07 15:29
I got the same results using the pretrained weights.

**Comment by thaithanhtuan** [comment] 2020-07-07 16:17
Sorry for this inconvenience. In a short term, please check the results generated from CPVTON+ in this google link. In this link, one version (that I can find quickly) of our paper result is presented with CPVTON.
https://drive.google.com/drive/folders/1fol0mMvrgjGE5lZlqR7y-7LhOOraU1wQ?usp=sharing
We will check the implementation and pretrained file soon. May be we upload wrong pretrained file. 
Thank for your comments.

**Comment by nandu749** [comment] 2020-07-07 16:22
what is the weight file named tom_with_hands_final.pth, is it replacement for tom_final.pth?

**Comment by thaithanhtuan** [comment] 2020-07-07 16:32
![image](https://user-images.githubusercontent.com/19486377/86812320-da2bae80-c0b9-11ea-9615-e48f4f994167.png)
The photos here are not fully shown. There are some good cases and some bad cases. I think the wrong results come from the new human semantic segmentation. This may lead to wrong results.
@nandu749 : all files in this google drive share are different from the previous share. tom_with_hands_final.pth is another experiment which is not included in the paper.

**Comment by nandu749** [comment] 2020-07-07 16:33
Ok I will check that out.

**Comment by nandu749** [comment] 2020-07-07 16:35
https://drive.google.com/drive/folders/1EpAtLa0P2rleekZw-jcp6YR91IKPRCh5?usp=sharing

**Comment by nandu749** [comment] 2020-07-07 16:36
I think above 90% are not good

**Comment by thaithanhtuan** [comment] 2020-07-07 17:01
@nandu749 I have just uploaded the image-parse-new and image-parse-new-vis. Can you kindly spend time on running test with these input!
https://drive.google.com/drive/folders/1fol0mMvrgjGE5lZlqR7y-7LhOOraU1wQ?usp=sharing

**Comment by nandu749** [comment] 2020-07-07 17:03
ohk

**Comment by phenomenal-manish** [comment] 2020-07-14 04:54
Hi @thaithanhtuan, Could you share your results with the image-parse-new and image-parse-new-vis in a google drive folder.

**Comment by thaithanhtuan** [comment] 2020-07-14 07:29
@phenomenal-manish I upload the image-parse-new and image-parse-new-vis for testing in here.
https://drive.google.com/drive/folders/1fol0mMvrgjGE5lZlqR7y-7LhOOraU1wQ?usp=sharing

**Comment by nandu749** [comment] 2020-07-14 07:32
How can we use it for warping pants?, is there any way?

**Comment by thaithanhtuan** [comment] 2020-07-14 07:35
@nandu749 To use this network for warping bottom clothes like pants or skirt, You must have a new dataset with pants or skirt as inshop cloth. You can crawl these data from internet. I think 2000 images is enough for warping pants.

**Comment by phenomenal-manish** [comment] 2020-07-14 10:23
> @phenomenal-manish I upload the image-parse-new and image-parse-new-vis for testing in here.
> https://drive.google.com/drive/folders/1fol0mMvrgjGE5lZlqR7y-7LhOOraU1wQ?usp=sharing

Hey, so I just need to run data_download.py, and place the image-parse-new and image-parse-new-vis in data folders right? After that I can just use pre-trained models(checkpoints) to generate results. Correct me if I'm wrong.

**Comment by minar09** [comment] 2020-07-14 10:34
@phenomenal-manish , yes, that's correct.

**Comment by nandu749** [comment] 2020-07-14 10:54
Can I combine both upper and lower cloths. Like swapping both shirt and
pant

**Comment by phenomenal-manish** [comment] 2020-07-14 11:24
> @phenomenal-manish , yes, that's correct.

Hi, I followed the steps, are you sure the checkpoint file is correct? 
Getting this error when I run test.py to generate warp cloths and mask for train data using gmm_final.pth.
![error](https://user-images.githubusercontent.com/24850992/87420266-9a515380-c5f2-11ea-86aa-0ee85717b851.PNG)

**Comment by minar09** [comment] 2020-07-14 11:26
@phenomenal-manish , use the checkpoints from the link given in the readme file. That's the tested one with the code.

**Comment by phenomenal-manish** [comment] 2020-07-14 11:30
> @phenomenal-manish , use the checkpoints from the link given in the readme file. That's the tested one with the code.

Sure, will do that.

**Comment by phenomenal-manish** [comment] 2020-07-14 14:19
Hey,
Results using the image-parse-new folder are similar to the ones posted by @nandu749 , tried testing on image-parse-new-vis but the results are worse than that of image-parse-new as input.

**Comment by minar09** [comment] 2020-07-14 14:25
@phenomenal-manish , did you run `body_binary_masking.py` file before testing? Its needed for body shape input.
And you should run with `image-parse-new` folder, `image-parse-new-vis` is for visualization only.

**Comment by phenomenal-manish** [comment] 2020-07-14 14:28
> @phenomenal-manish , did you run `body_binary_masking.py` file before testing? Its needed for body shape input.
> And you should run with `image-parse-new` folder, `image-parse-new-vis` is for visualization only.

Yes, I ran body_binary_masking.py twice on test data as stated in readme.md, and ran with image-parse-new folder. Should I upload the results on drive?

**Comment by minar09** [comment] 2020-07-14 14:34
Hi @phenomenal-manish , no need to upload your results. I guess if you did everything in order and correctly, the results should be okay. You can try debugging with small umber images also. However, if the issues still persist, its better if you train you own models. Sorry for your inconvenience. Thank you.

**Comment by phenomenal-manish** [comment] 2020-07-14 14:46
Had a small doubt, could you clarify why do we need to run dataset_neck_skin_correction.py & body_binary_masking.py twice?

**Comment by minar09** [comment] 2020-07-14 14:50
Actually, by twice I meant for both train and test data. You need to set the correct paths in the script before running for different data.

**Comment by phenomenal-manish** [comment] 2020-07-14 14:52
Yes, that I could understand by looking the code. As you just need to uncomment/comment the lines as per train/test data.

**Comment by phenomenal-manish** [comment] 2020-07-14 14:54
> Hi @phenomenal-manish , no need to upload your results. I guess if you did everything in order and correctly, the results should be okay. You can try debugging with small number of images also. However, if the issues still persist, its better if you train you own models. Sorry for your inconvenience. Thank you.

I'll try training the models. Thanks for the quick replies.

**Comment by minar09** [comment] 2020-07-14 16:05
Hi @phenomenal-manish , @armheb , @nandu749 , just to let you know that, to be confirmed about the checkpoints, I just test the repository from start, and the results look like below. So, I think if you generated the corrected segmentation files and binary masks correctly, test results should be as expected. Otherwise, training from scratch is the only option (It doesn't take long). Thank you for trying out our codes.

![image](https://user-images.githubusercontent.com/3684134/87448544-f50c9e80-c636-11ea-8e26-7c97903562d6.png)

**Comment by phenomenal-manish** [comment] 2020-07-15 09:25
Hi @nandu749 ,
Is it possible for you to share the colab notebook for cp-vton-plus?

**Comment by abhiagwl4262** [comment] 2020-07-18 18:27
hey @minar09, I would like to add few points. The new segmentation masks do not seem to be accurate. I am putting few images just for comparison. Can you explain that ?

**Comment by minar09** [comment] 2020-07-19 02:35
Hi @abhiagwl4262 , thanks for pointing out the issue.  The dataset_neck_skin_correction.py is not a trained model for predicting segmentation, which is just a heuristic approach to automatically detect the neck/chest skin area and assign a new label. Obviously, it does not work 100% correctly, you may get different results if you run again.

The whole point of doing this segmentation correction, is to fix the artifacts that were caused due to labeling the neck skin area as background in the VITON dataset segmentation. If you see the CP-VTON try-on results, you will find that try-on result with a different cloth has a shape similar to the source cloth, which is wrong. Hence, we made this dataset_neck_skin_correction.py script to correct the segmentation by assigning a new label to neck-skin. Its not mandatory that you need to run dataset_neck_skin_correction.py for getting better results. 

@thaithanhtuan already shared the corrected segmentation from our final results, you can make use of it for your testing. For more better results, I would recommend using predicted segmentation by CIHP_PGN pretrained network, which a torso-skin label and produces better segmentation prediction. I hope this answers your questions. Please feel free to ask if you have any questions. Thank you.

**Comment by minar09** [comment] 2020-07-19 03:52
I am not sure how you produced those segmentation files, but I just ran the dataset_neck_skin_correction.py for test data again, and the results look like below. I also updated the dataset_neck_skin_correction.py script to save the visualized segmentation files as well, so you can compare it with the original ones. Hope that helps. Thank you.

![image](https://user-images.githubusercontent.com/3684134/87866570-7315d000-c9be-11ea-9193-c580f58e4f00.png)

**Comment by abhiagwl4262** [comment] 2020-07-22 15:13
@minar09  I am using your code as it is. And I am getting following segmentation maps -  

![image](https://user-images.githubusercontent.com/22645080/88194016-ef790f00-cc5b-11ea-9301-868ae74585a5.png)

**Comment by minar09** [comment] 2020-07-23 06:53
@abhiagwl4262 , that's strange to me, I get the same results every time as I showed previously. What is your environment and how did you run the code? I ran in windows-anaconda-python-3 environment. And to run this code, I have the VITON dataset images and original segmentation in "image" and "image-parse" folders.

**Comment by abhiagwl4262** [comment] 2020-07-23 08:18
@minar09 I downloaded data with data_download.py. I am running on Linux machine with python3, opencv-4.1, pillow-5.4.

**Comment by minar09** [comment] 2020-07-24 06:46
@abhiagwl4262 , I will try to run in a different env like yours and let you know.

**Comment by minar09** [comment] 2020-07-31 09:58
I think these issues are due to "os.listdir" function, acting differently in different OSes, solved here: https://github.com/minar09/cp-vton-plus/issues/8#issuecomment-667022408 #8

**Comment by RubReh** [comment] 2020-07-31 15:29
Will pull request the fix for this soon! @abhiagwl4262 , @minar09 
I got it working for GMM part but still some sort of mismatch of files when running TOM.

**Comment by minar09** [comment] 2020-08-01 01:00
@RubReh, that sounds awesome.  Thank you so much.

**Comment by abhiagwl4262** [comment] 2020-08-02 15:52
@minar09 Oh yeah. I used sorted and It got resolved.

**Comment by minar09** [comment] 2020-09-13 05:27
Closing the issue as its resolved. Feel free to reopen in case there are still problems.

**Closed by minar09** 2020-09-13 05:27 UTC
